name: Node CI

on:
  push:
    branches: 
      - based_rust
  schedule:
      - cron: "0 0 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: rust_env
      shell: bash
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, build, and test
      run: |
        npm install -g yarn
        yarn
        yarn build
      env:
        CI: true
    - name: Auto green
      run: |
        git config --local user.email "guzhongren@live.cn"
        git config --local user.name "guzhongren"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
        git checkout based_rust
        git pull --rebase
        date +"%Y-%m-%d %H:%M:%S.%N" > keepchange.txt
        git add .
        git commit -am "a commit a day keeps your girlfriend away"
        git push
